### ISSUE TITLE
Can't enable camera again - macOS BigSur

### ISSUE THREAD

**Issue by ghost** [rthomson/isight-disabler#10]
Installed the isight disabler in 2016 I can't enable the camera now again. In the meantime Apple has changed to macOS BigSur. What can I do? I'm not a professionel, so I do unfortunately have no coding skills. Thanks in advance!

**Comment by rthomson** [comment]
macOS has changed a lot over the years with regards to iSight/FaceTime camera, drivers and just macOS in general - so the situation is potentially complex with regards to when you originally disabled it, what version of macOS it was, what version you're running now, etc.

The most straight-forward solution reported by others is re-installation of macOS. See issue #9 for some tips on other options (and confirmation of a successful re-install) but the most reliable and simple answer is probably to re-install macOS.
