### ISSUE TITLE
Not up-to-date for El Capitan?

### ISSUE THREAD

**Issue by JayBrown** [rthomson/isight-disabler#2]
It doesn't seem to be up-to-date for El Capitan:
- The following executable is ignored:
  `/Library/CoreMediaIO/Plug-Ins/FCP-DAL/AppleCamera.plugin/Contents/MacOS/AppleCamera`
- The following private frameworks does not exist anymore:

```
/System/Library/PrivateFrameworks/CoreMediaIOServices.framework
```

Therefore the executable at `./Versions/A/Resources/VDC.plugin/Contents/MacOS/VDC` doesn't exist anymore either.
- The following executable does not exist anymore:

`/System/Library/PrivateFrameworks/CoreMediaIOServicesPrivate.framework/Versions/A/Resources/VDC.plugin/Contents/MacOS/VDC`

Instead there is another executable:

`/System/Library/PrivateFrameworks/CoreMediaIOServicesPrivate.framework/Versions/A/Resources/AVC.plugin/Contents/MacOS/AVC`

What's up with this one?

Please note that the script still works in El Capitan if you disable SIP.

**Comment by rthomson** [comment]
Thanks for report. I'm not sure what's up with the VDC vs. AVC plugin. Apple has been known to make several changes to the drivers and core libraries along the way.

The script itself could use an update for El Capitan given the changes and to keep things consistent but since you report it's still working, I'll probably just wait for a pull request or leave things as is for now.

**Comment by JayBrown** [comment]
It could be that the AVC is a driver for newer Macs. Apple did change the name of the camera somewhere along the line. I still have an older 2010 MBP with the old iSight camera. If nobody else reports back, I'll do so when I have the new 2016 MBP. :)

**Comment by stecrv** [comment]
As temporary workaround
1. please restart OSX
2. load recovery mode (Command + R)
3. open utility, terminal
4. insert `csrutil disable`

Please remember to set `csrutil enable`

**Comment by goldenis** [comment]
@rthomson I've disabled isight using this plugin but can't enable it back.

I'm on iOS 10.11.6

Thanks.

**Comment by JayBrown** [comment]
You mean macOS 10.11.6, right? If you want to disable or re-enable iSight on 10.11.6 (my system as well), you need to have SIP disabled whenever you want to do one of the two operations. If you don't want to disable SIP, you need to use the mobileconfig solution. (Don't know where this is posted, though.)

I use the following commands without AppleScript, but with a shell script, and it has always worked.

**Disable**

```
sudo chmod a-r /System/Library/Frameworks/CoreMediaIO.framework/Versions/A/Resources/VDC.plugin/Contents/MacOS/VDC
sudo chmod a-r /System/Library/PrivateFrameworks/CoreMediaIOServicesPrivate.framework/Versions/A/Resources/AVC.plugin/Contents/MacOS/AVC
sudo chmod a-r /System/Library/QuickTime/QuickTimeUSBVDCDigitizer.component/Contents/MacOS/QuickTimeUSBVDCDigitizer
sudo chmod a-r /Library/CoreMediaIO/Plug-Ins/DAL/AppleCamera.plugin/Contents/MacOS/AppleCamera
sudo chmod a-r /Library/CoreMediaIO/Plug-Ins/FCP-DAL/AppleCamera.plugin/Contents/MacOS/AppleCamera
```

**Re-enable**

```
sudo chmod a+r /System/Library/Frameworks/CoreMediaIO.framework/Versions/A/Resources/VDC.plugin/Contents/MacOS/VDC
sudo chmod a+r /System/Library/PrivateFrameworks/CoreMediaIOServicesPrivate.framework/Versions/A/Resources/AVC.plugin/Contents/MacOS/AVC
sudo chmod a+r /System/Library/QuickTime/QuickTimeUSBVDCDigitizer.component/Contents/MacOS/QuickTimeUSBVDCDigitizer
sudo chmod a+r /Library/CoreMediaIO/Plug-Ins/DAL/AppleCamera.plugin/Contents/MacOS/AppleCamera
sudo chmod a+r /Library/CoreMediaIO/Plug-Ins/FCP-DAL/AppleCamera.plugin/Contents/MacOS/AppleCamera
```

If this still doesn't work, you should run a search on your boot volume for "VDC", "AVC", and "AppleCamera", not with spotlight, but with an app like **EasyFind**. If you find another path to an iSight driver executable in addition to the ones above, you need to run the chmod command on that executable as well… and post it here. :) But since you managed to disable iSight, you've probably already chmodded all the right ones.
