### ISSUE TITLE
Error on Sierra

### ISSUE THREAD

**Issue by funky-monkey** [rthomson/isight-disabler#3]
Hello, 

I'm getting an error when I run this on macOS Sierra. When your script runs, I do pass in the correct password to make it run.

```
chmod: Unable to change file mode on /System/Library/QuickTime/QuickTimeUSBVDCDigitizer.component/Contents/MacOS/QuickTimeUSBVDCDigitizer: Operation not permitted
chmod: Unable to change file mode on /System/Library/Frameworks/CoreMediaIO.framework/Versions/A/Resources/VDC.plugin/Contents/MacOS/VDC: Operation not permitted
```

Any ideas?

**Comment by stecrv** [comment]
Within the last update, some part of mac OS can be changed only under special conditions or disabling "System Integrity Protection"

please read [https://forums.developer.apple.com/thread/4138](https://forums.developer.apple.com/thread/4138)
