### ISSUE TITLE
10.12.6

### ISSUE THREAD

**Issue by loic-lopez** [rthomson/isight-disabler#6]
Hi, i have tried to run your app but with MacOS sierra is not working : 
when i disable iSight i can not use the camera anymore

**Comment by rthomson** [comment]
@Lopez-i Not sure what the issue is. You can disable the camera, but can't re-enable?

Are you using https://github.com/rthomson/isight-disabler/blob/master/camera-disabler.mobileconfig or https://github.com/rthomson/isight-disabler/blob/master/isight-disabler.scpt?

**Comment by mehdi9000** [comment]
Does not work on MacOS 10.13.0 "High Sierra."

**Comment by octoviaa** [comment]
The profile does properly disabled the camera unfortunately FaceTime won't load hence I'm not able to make voice only call with FaceTime. (macOS 10.13.2).

UPDATE:
I tried using FaceTime voice from the 'contact' application and it works.

Hope this will help other people
