### ISSUE TITLE
iSight Disabler on Mojave

### ISSUE THREAD

**Issue by zv09** [rthomson/isight-disabler#8]
Hi, 
Would anybody update this script for macOS X Mojave. 
Its return with error in the current build

**Comment by julianheusel** [comment]
Hi Vitaly,
I think the problem is SIP (https://support.apple.com/en-us/HT204899).
There are some tools to deactivate SIP but this is not what I recommend to do...

**Comment by rthomson** [comment]
See https://github.com/rthomson/isight-disabler/blob/master/camera-disabler.mobileconfig as a modern alternative to the original iSight Disabler AppleScript.
